### ISSUE TITLE
Enable more `eslint-plugin-import` rules

### ISSUE THREAD

**Issue by sindresorhus** [xojs/xo#124]
Follow-up to https://github.com/sindresorhus/xo/pull/109.

Some are disabled because of issues. Help welcome! :)

https://github.com/sindresorhus/xo/blob/master/config/plugins.js#L20
## 
- [ ] Ignore CommonJS exports in the `named` rule: https://github.com/benmosher/eslint-plugin-import/issues/268
- [ ] Add ability to ignore certain packages from all rules: https://github.com/benmosher/eslint-plugin-import/issues/275
- [x] Lodash modularized libs cause false positive for `import/extensions` https://github.com/benmosher/eslint-plugin-import/issues/378

**Comment by sindresorhus** [comment]
I'm more likely to use less rules. That plugin is super buggy and not that actively maintained.
